apiVersion: v1
kind: Service
metadata:
  name: devops-demo-service
  labels:
    app: devops-demo
spec:
  type: ClusterIP
  selector:
    app: devops-demo
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
